version: "3.9"

# start with the following command to let services connect to each other
# docker-compose --project-name getting-started-guide up --build

services:
  testdata2edc:
    container_name: testdata2edc
    build: ./
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - "${TESTDATA_FILE:-./OEMA_HYBRID_VEHICLES_10_fix8.json}:/code/testdata_file.json"
    env_file:
      - .env
