# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from .base_model import MyBaseModel
from pydantic import AnyUrl, EmailStr, validator, Field  # noqa: F401
from aas.registry.models.protocol_information import ProtocolInformation


class Endpoint(MyBaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Endpoint - a model defined in OpenAPI

        interface: The interface of this Endpoint.
        protocol_information: The protocol_information of this Endpoint.
    """

    interface: str
    protocol_information: ProtocolInformation = Field(None, alias='protocolInformation')

Endpoint.update_forward_refs()
