# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from .base_model import MyBaseModel
from pydantic import AnyUrl, EmailStr, validator  # noqa: F401


class IdentifierKeyValuePairAllOf(MyBaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    IdentifierKeyValuePairAllOf - a model defined in OpenAPI

        key: The key of this IdentifierKeyValuePairAllOf.
        value: The value of this IdentifierKeyValuePairAllOf.
    """

    key: str
    value: str

    @validator("key")
    def key_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("key")
    def key_max_length(cls, value):
        assert len(value) <= 200
        return value

    @validator("value")
    def value_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("value")
    def value_max_length(cls, value):
        assert len(value) <= 200
        return value

IdentifierKeyValuePairAllOf.update_forward_refs()
