# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from .base_model import MyBaseModel
from pydantic import AnyUrl, EmailStr, validator  # noqa: F401
from aas.registry.models.has_semantics import HasSemantics
from aas.registry.models.identifier_key_value_pair_all_of import IdentifierKeyValuePairAllOf
from aas.registry.models.reference import Reference


class IdentifierKeyValuePair(MyBaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    IdentifierKeyValuePair - a model defined in OpenAPI

        semantic_id: The semantic_id of this IdentifierKeyValuePair [Optional].
        key: The key of this IdentifierKeyValuePair.
        value: The value of this IdentifierKeyValuePair.
    """

    semantic_id: Optional[Reference] = None
    key: str
    value: str

    @validator("key")
    def key_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("key")
    def key_max_length(cls, value):
        assert len(value) <= 200
        return value

    @validator("value")
    def value_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("value")
    def value_max_length(cls, value):
        assert len(value) <= 200
        return value

IdentifierKeyValuePair.update_forward_refs()
