# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from .base_model import MyBaseModel
from pydantic import AnyUrl, BaseModel, EmailStr, validator  # noqa: F401


class LangString(MyBaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    LangString - a model defined in OpenAPI

        language: The language of this LangString.
        text: The text of this LangString.
    """

    language: str
    text: str

    @validator("language")
    def language_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("language")
    def language_max_length(cls, value):
        assert len(value) <= 10
        return value

    @validator("text")
    def text_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("text")
    def text_max_length(cls, value):
        assert len(value) <= 500
        return value

LangString.update_forward_refs()
