# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from .base_model import MyBaseModel
from pydantic import AnyUrl, EmailStr, validator  # noqa: F401
from aas.registry.models.global_reference import GlobalReference


class Reference(MyBaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Reference - a model defined in OpenAPI

        value: The value of this Reference.
    """

    value: List[str]

Reference.update_forward_refs()
