# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from .base_model import MyBaseModel
from pydantic import AnyUrl, EmailStr, validator, Field  # noqa: F401
from aas.registry.models.administrative_information import AdministrativeInformation
from aas.registry.models.descriptor import Descriptor
from aas.registry.models.endpoint import Endpoint
from aas.registry.models.lang_string import LangString
from aas.registry.models.reference import Reference


class SubmodelDescriptor(MyBaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SubmodelDescriptor - a model defined in OpenAPI

        administration: The administration of this SubmodelDescriptor [Optional].
        description: The description of this SubmodelDescriptor [Optional].
        id_short: The id_short of this SubmodelDescriptor [Optional].
        identification: The identification of this SubmodelDescriptor.
        semantic_id: The semantic_id of this SubmodelDescriptor.
        endpoints: The endpoints of this SubmodelDescriptor.
    """

    administration: Optional[AdministrativeInformation] = None
    description: Optional[List[LangString]] = None
    id_short: Optional[str] = Field(None, alias='idShort')
    identification: str
    semantic_id: Reference = Field(None, alias='semanticId')
    endpoints: List[Endpoint]

    @validator("id_short")
    def id_short_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("id_short")
    def id_short_max_length(cls, value):
        assert len(value) <= 100
        return value

    @validator("identification")
    def identification_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("identification")
    def identification_max_length(cls, value):
        assert len(value) <= 200
        return value

SubmodelDescriptor.update_forward_refs()
